### ISSUE TITLE
Maintaining offer!

### ISSUE THREAD

**Issue by GuillouTran** [KindleManga/Kindlemanga#18]
Hi guys,

Understanding that you guy are not maintaining this repository, can I take over it then? Because I used you stuff before and really enjoy the principle of it, especially that I used kindle a lot. I could continually maintain it if you want!

**Comment by tudoanh** [comment]
You could just folk the code and then update, deploy by yourself, if that what's you mean by "maintaining".
Otherwise if you only offer the server/domain costs, that's not what this project needs right now.

**Comment by GuillouTran** [comment]
Fair enough!

**Comment by tudoanh** [comment]
From what I see, you just need to figure out how to download image from Cloudflare Raytracing, and update the uploader part to your favorite host. And maybe update the crawler parts.
